# Generated by Django 3.2.7 on 2023-04-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0002_babysitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('typee', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
