# Generated by Django 3.2.7 on 2023-04-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0003_doctor_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='baby_enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('pid', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
