# Generated by Django 3.2.7 on 2023-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0006_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitter_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bs_id', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('date_frm', models.CharField(max_length=150)),
                ('date_to', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
    ]
