# Generated by Django 3.2.7 on 2023-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0007_sitter_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter_request',
            name='status',
            field=models.CharField(default=4, max_length=150),
            preserve_default=False,
        ),
    ]
