# Generated by Django 3.2.7 on 2023-04-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0008_sitter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter_request',
            name='p_id',
            field=models.CharField(default=3, max_length=150),
            preserve_default=False,
        ),
    ]
