# Generated by Django 3.2.7 on 2023-04-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0011_nutrition_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_request',
            name='basicpay',
            field=models.CharField(default=500, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition_request',
            name='basicpay',
            field=models.CharField(default=500, max_length=150),
            preserve_default=False,
        ),
    ]
