# Generated by Django 3.2.7 on 2023-04-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0012_auto_20230404_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.CharField(max_length=150)),
                ('p_id', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
