# Generated by Django 3.2.7 on 2023-04-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0013_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_request',
            name='p_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition_request',
            name='p_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
