# Generated by Django 3.2.7 on 2023-04-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0014_auto_20230404_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=150)),
                ('basicpay', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('cvv', models.CharField(max_length=150)),
            ],
        ),
    ]
