# Generated by Django 3.2.7 on 2023-04-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0015_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=150)),
                ('vaccine', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('p_id', models.CharField(max_length=150)),
            ],
        ),
    ]
