# Generated by Django 3.2.7 on 2024-06-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0017_baby_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='dreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
