# Generated by Django 3.2.7 on 2024-07-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0019_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby_enroll',
            name='daycare',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
