# Generated by Django 3.2.12 on 2024-07-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0020_baby_enroll_daycare'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='daycare_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='daycare_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionists',
            name='daycare_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
