# Generated by Django 3.2.12 on 2024-07-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0021_auto_20240715_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_request',
            name='daycare_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition_request',
            name='daycare_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter_request',
            name='daycare_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
