# Generated by Django 3.2.12 on 2024-07-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0022_auto_20240715_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition_request',
            name='daycare_id',
        ),
    ]
