# Generated by Django 3.2.12 on 2024-07-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0023_remove_nutrition_request_daycare_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition_request',
            name='daycare_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
