# Generated by Django 3.2.12 on 2024-07-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0024_nutrition_request_daycare_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='b_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='daycare_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='p_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
